spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
              create-source: metadata
  flyway:
    enabled: false

multi-tenancy:
  tenants:
    - tenantId: eventsourcing
      url: jdbc:h2:mem:albums-axon-db
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
    - tenantId: projections
      url: jdbc:h2:mem:albums-projections-db
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
