spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false

multi-tenancy:
  tenants:
    - tenantId: eventsourcing
      url: jdbc:h2:file:./albums-axon;COMPRESS=TRUE;DB_CLOSE_ON_EXIT=FALSE
      username: albums
      password: albums
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration/axon
    - tenantId: projections
      url: jdbc:h2:file:./albums-projections;COMPRESS=TRUE;DB_CLOSE_ON_EXIT=FALSE
      username: albums
      password: albums
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration/projections
    - tenantId: thumbnails
      url: jdbc:h2:file:./albums-thumbnails;COMPRESS=TRUE;DB_CLOSE_ON_EXIT=FALSE
      username: albums
      password: albums
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration/thumbnails
    - tenantId: auditLog
      url: jdbc:h2:file:./albums-audit-log;COMPRESS=TRUE;DB_CLOSE_ON_EXIT=FALSE
      username: albums
      password: albums
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration/audit-log

cors:
  maxAge: "3600"
  origins:
    - "http://localhost:8080"

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  eventhandling:
    processors:
      picture-analysis:
        threadCount: 8
        initialSegmentCount: 8

logging:
  level:
    root: info

picture-aggregate:
  color-palette-size: 5
  snapshot-trigger-threshold: 100
  thumbnail-size: 200
  hashing-sample-size: 100
  duplicate-similarity: 0.82
  auto-crop-tolerance: 0.4
