spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false

multi-tenancy:
  tenants:
    - tenantId: eventsourcing
      url: "jdbc:mariadb://localhost:3306/eventsourcing"
      username: root
      password: secret
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration/axon
    - tenantId: projections
      url: "jdbc:mariadb://localhost:3306/projections"
      username: root
      password: secret
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration/projections
    - tenantId: thumbnails
      url: "jdbc:mariadb://localhost:3306/thumbnails"
      username: root
      password: secret
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration/thumbnails
    - tenantId: auditLog
      url: "jdbc:mariadb://localhost:3306/audit_log"
      username: root
      password: secret
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration/audit-log

cors:
  maxAge: "3600"
  origins:
    - "http://localhost:8080"

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  eventhandling:
    processors:
      picture-analysis:
        initialSegmentCount: 8
      projections:
        initialSegmentCount: 4
      audit:
        initialSegmentCount: 2

logging:
  level:
    root: info

picture-aggregate:
  color-palette-size: 5
  snapshot-trigger-threshold: 10
  thumbnail-size: 200
  hashing-sample-size: 100
  duplicate-similarity: 0.82
  auto-crop-tolerance: 0.4
