spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
              create-source: metadata
  flyway:
    enabled: false

multi-tenancy:
  tenants:
    - tenantId: eventsourcing
      url: "jdbc:mariadb://localhost:3306/temp"
      username: root
      password: secret
    - tenantId: projections
      url: "jdbc:mariadb://localhost:3306/temp"
      username: root
      password: secret
    - tenantId: thumbnails
      url: "jdbc:mariadb://localhost:3306/temp"
      username: root
      password: secret
    - tenantId: auditLog
      url: "jdbc:mariadb://localhost:3306/temp"
      username: root
      password: secret
