name: CI

on: [ push ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-modules
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Compile and run tests
        run: mvn -B test

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-modules
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-build
          restore-keys: ${{ runner.os }}-m2
      - name: Build package
        run: mvn -B package -DskipTests
      - name: Stage artifacts
        run: mkdir staging && cp reactive-albums-api/target/*.jar staging
      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          name: Reactive Albums Boot Jar
          path: staging


